### ISSUE TITLE
way to introduce minifiers?

### ISSUE THREAD

**Issue by haoliangyu** [NathanMarq/scaffold#22]
Days ago we discussed about the introduction of minifier for HTML and images. As the app now is directly serving the source HTML and image files, it will require to move the source files and leave the space for the optimized files. 

How do you think moving the source files in `public` folder to the `public_src` folder, and create tasks for optimization and placing optimized files to `public` folder?

**Comment by jvgriffis** [comment]
Are we really talking about adding minifiers for html and images? I think
in 2016 if we're not in the top million websites in the world, I believe
that's what I'd call "premature."

Just make sure the web server is using gzip and call it a day. I suspect
there's a hundred other enhancements that'll do more good, like dumping
grunt, gulp and all that nonsense for npm scripts... Focus....
